### ISSUE TITLE
Clicking anywhere in an EpicSMP inventory throws an Exception

### ISSUE THREAD

**Issue by JustBru00** [JustBru00/EpicSMP#11]
[20:50:38] [Server thread/ERROR]: Could not pass event InventoryClickEvent to EpicSMP v1.3.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.14.jar:git-Spigot-e4be9b0-f4f3295]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.jar:git-Spigot-e4be9b0-f4f3295]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) ~[spigot-1.14.jar:git-Spigot-e4be9b0-f4f3295]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) ~[spigot-1.14.jar:git-Spigot-e4be9b0-f4f3295]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2159) ~[spigot-1.14.jar:git-Spigot-e4be9b0-f4f3295]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot-1.14.jar:git-Spigot-e4be9b0-f4f3295]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.14.jar:git-Spigot-e4be9b0-f4f3295]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.jar:git-Spigot-e4be9b0-f4f3295]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.jar:git-Spigot-e4be9b0-f4f3295]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.jar:git-Spigot-e4be9b0-f4f3295]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.jar:git-Spigot-e4be9b0-f4f3295]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.jar:git-Spigot-e4be9b0-f4f3295]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:892) [spigot-1.14.jar:git-Spigot-e4be9b0-f4f3295]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:885) [spigot-1.14.jar:git-Spigot-e4be9b0-f4f3295]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot-1.14.jar:git-Spigot-e4be9b0-f4f3295]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:869) [spigot-1.14.jar:git-Spigot-e4be9b0-f4f3295]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:802) [spigot-1.14.jar:git-Spigot-e4be9b0-f4f3295]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getName()Ljava/lang/String;
        at com.gmail.justbru00.epic.smp.Listeners.Listener.InventoryClick(Listener.java:112) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:311) ~[spigot-1.14.jar:git-Spigot-e4be9b0-f4f3295]
        ... 17 more

**Comment by JustBru00** [comment]
Closed by f29f3a7afad5077eddab71e293a8da8a704eae52
