### ISSUE TITLE
ERROR: NullPointer

### ISSUE THREAD

**Issue by JustBru00** [JustBru00/EpicSMP#13]
Reported by @Bloodlex on spigotmc.org

That's the exact plugin I need! But unfortunately it throws errors like that one:

05.07 18:22:33 [Server] ERROR Could not pass event PlayerInteractEvent to EpicSMP v1.4
05.07 18:22:33 [Server] INFO java.lang.NullPointerException: null
05.07 18:22:33 [Server] INFO at com.gmail.justbru00.epic.smp.Listeners.Listener.onPlayerInteract(Listener.java:64) ~[?:?]
05.07 18:22:33 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor214.execute(Unknown Source) ~[?:?]
05.07 18:22:33 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-375]
05.07 18:22:33 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-375]
05.07 18:22:33 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-375]
05.07 18:22:33 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-375]
05.07 18:22:33 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:471) ~[patched_1.15.2.jar:git-Paper-375]
05.07 18:22:33 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:438) ~[patched_1.15.2.jar:git-Paper-375]
05.07 18:22:33 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:434) ~[patched_1.15.2.jar:git-Paper-375]
05.07 18:22:33 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1462) ~[patched_1.15.2.jar:git-Paper-375]
05.07 18:22:33 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[patched_1.15.2.jar:git-Paper-375]
05.07 18:22:33 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.15.2.jar:git-Paper-375]
05.07 18:22:33 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-375]
05.07 18:22:33 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-375]
05.07 18:22:33 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-375]
05.07 18:22:33 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-375]
05.07 18:22:33 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-375]
05.07 18:22:33 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1105) ~[patched_1.15.2.jar:git-Paper-375]
05.07 18:22:33 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1098) ~[patched_1.15.2.jar:git-Paper-375]
05.07 18:22:33 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-375]
05.07 18:22:33 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1059) ~[patched_1.15.2.jar:git-Paper-375]
05.07 18:22:33 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:974) ~[patched_1.15.2.jar:git-Paper-375]
05.07 18:22:33 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

**Comment by JustBru00** [comment]
Looking at source the only thing I can guess is that `player` is null somehow.
https://github.com/JustBru00/EpicSMP/blob/master/src/com/gmail/justbru00/epic/smp/Listeners/Listener.java#L64

A simple null check on `player` may fix the issue. Will need to see if I can reproduce the issue.
https://github.com/JustBru00/EpicSMP/blob/master/src/com/gmail/justbru00/epic/smp/Listeners/Listener.java#L55
```
final Player player = e.getPlayer();
        
        ArrayList<String> testlore = new ArrayList<String>();
    	testlore.add(Messager.color("&7Right click in the air to deposit this."));
    	testlore.add(Messager.color(Main.Prefix));
    	
    	
    	if (e.getAction() != Action.RIGHT_CLICK_AIR) return;
    	
    	if (player.getInventory().getItemInMainHand().getItemMeta().getLore() == null) return;
```
