### ISSUE TITLE
Last /withdraw note throws error when depositing. (but it still works)

### ISSUE THREAD

**Issue by JustBru00** [JustBru00/EpicSMP#9]
Version: 1.12-pre2
```[08:11:29 FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AssertionError: TRAP
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_131]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_131]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:47) [spigot-1.12-pre2.jar:git-Spigot-429b0e3-5195487]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12-pre2.jar:git-Spigot-429b0e3-5195487]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12-pre2.jar:git-Spigot-429b0e3-5195487]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12-pre2.jar:git-Spigot-429b0e3-5195487]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12-pre2.jar:git-Spigot-429b0e3-5195487]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.AssertionError: TRAP
        at net.minecraft.server.v1_12_R1.ItemStack.F(ItemStack.java:100) ~[spigot-1.12-pre2.jar:git-Spigot-429b0e3-5195487]
        at net.minecraft.server.v1_12_R1.ItemStack.setCount(ItemStack.java:832) ~[spigot-1.12-pre2.jar:git-Spigot-429b0e3-5195487]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:403) ~[spigot-1.12-pre2.jar:git-Spigot-429b0e3-5195487]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:977) ~[spigot-1.12-pre2.jar:git-Spigot-429b0e3-5195487]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) ~[spigot-1.12-pre2.jar:git-Spigot-429b0e3-5195487]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) ~[spigot-1.12-pre2.jar:git-Spigot-429b0e3-5195487]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[spigot-1.12-pre2.jar:git-Spigot-429b0e3-5195487]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_131]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[spigot-1.12-pre2.jar:git-Spigot-429b0e3-5195487]
        ... 5 more
[08:11:42 INFO]: JustBru00 issued server command: /withdraw 1000
[08:11:43 INFO]: JustBru00 issued server command: /withdraw 1000
[08:11:43 INFO]: JustBru00 issued server command: /withdraw 1000
[08:11:44 INFO]: JustBru00 issued server command: /withdraw 1000
[08:11:49 FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AssertionError: TRAP
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_131]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_131]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:47) [spigot-1.12-pre2.jar:git-Spigot-429b0e3-5195487]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12-pre2.jar:git-Spigot-429b0e3-5195487]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12-pre2.jar:git-Spigot-429b0e3-5195487]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12-pre2.jar:git-Spigot-429b0e3-5195487]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12-pre2.jar:git-Spigot-429b0e3-5195487]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.AssertionError: TRAP
        at net.minecraft.server.v1_12_R1.ItemStack.F(ItemStack.java:100) ~[spigot-1.12-pre2.jar:git-Spigot-429b0e3-5195487]
        at net.minecraft.server.v1_12_R1.ItemStack.setCount(ItemStack.java:832) ~[spigot-1.12-pre2.jar:git-Spigot-429b0e3-5195487]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:403) ~[spigot-1.12-pre2.jar:git-Spigot-429b0e3-5195487]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:977) ~[spigot-1.12-pre2.jar:git-Spigot-429b0e3-5195487]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) ~[spigot-1.12-pre2.jar:git-Spigot-429b0e3-5195487]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) ~[spigot-1.12-pre2.jar:git-Spigot-429b0e3-5195487]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[spigot-1.12-pre2.jar:git-Spigot-429b0e3-5195487]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_131]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[spigot-1.12-pre2.jar:git-Spigot-429b0e3-5195487]
        ... 5 more```

**Comment by JustBru00** [comment]
Checked on ` This server is running CraftBukkit version git-Spigot-8cbfc85-ec47e79 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)` could not reproduce. @ComputerDude says it can be fixed by canceling the event after all code is run.
